version: '3.0'

services:

  kafka:
    image: spotify/kafkaproxy:latest
    ports:
      - 2181:2181
      - 9092:9092
      - 7203:7203
      - 80:80
    expose:
      - 2181
      - 9092
      - 7203
      - 80
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      CONSUMER_THREADS: 1
      TOPICS: myTopic,some-other-topic
      ZK_CONNECT: kafka7zookeeper:2181/root/path
      GROUP_ID: mymirror
    volumes:
      - ./volumes/kafka/:/kafka

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    links:
      - kafka
    expose:
      - 8000
    ports:
      - 8000:8000

    environment:
      KAFKA_REST_PROXY_URL: http://kafka

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    links:
      - kafka:zk
    expose:
      - 9000
    ports:
      - 9000:9000


  spark-master:
      build:
        context: spark-2
      image: spark-2:dev
      command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
      hostname: spark-master
      environment:
        MASTER: spark://spark-master:7077
        SPARK_CONF_DIR: /conf
        SPARK_PUBLIC_DNS: 127.0.0.1
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7006
        - 7077
        - 6066
        - 8080
      ports:
        - 4040:4040
        - 6066:6066
        - 7077:7077
        - 8080:8088
      volumes:
        - ./volumes/spark/conf/spark-master:/conf
        - ./volumes/spark/data:/tmp/data

  spark-worker:
      image: spark-2:dev
      command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
      hostname: spark-worker
      environment:
        SPARK_CONF_DIR: /conf
        SPARK_PUBLIC_DNS: 127.0.0.1
        SPARK_WORKER_CORES: 1
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8881
        SPARK_WORKER_WEBUI_PORT: 8081
      links:
        - spark-master
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 7016
        - 8881
      volumes:
        - ./volumes/spark/conf/spark-worker:/conf
        - ./volumes/spark/data:/tmp/data

  cassandra-master:
    image: cassandra:latest
    container_name: cassandra-master
    ports:
      - 9042:9042
      - 7199:7199
    volumes:
      - ./volumes/cassandra-master/data:/var/lib/cassandra

  cassandra-seed:
    image: cassandra:latest
    container_name: cassandra-seed
    ports:
      - 9142:9042
    links:
      - cassandra-master:seed
    environment:
      - CASSANDRA_SEEDS=seed
    volumes:
      - ./volumes/cassandra-seed/data:/var/lib/cassandra

  zeppelin:
    image: xemuliam/zeppelin:latest
    container_name: zeppelin
    ports:
      - 8081:8080
    expose:
      - 8080
      - 7077
      - 4040
    links:
      - cassandra-master